### PR TITLE
Removing JoinConversation

### PR DESCRIPTION
**Pull request by SoniaisMad**
### Description

https://github.com/ResultadosDigitais/hellper/issues/139

I removed the JoinConversation Call liked it was suggested in the issue.

### How to test?

the test should not fail

### Expected behavior
No behavior changed

### Link to the issue
https://github.com/ResultadosDigitais/hellper/issues/139

### CODE REVIEW

**Comment by SoniaisMad** [comment]
I dont know why but the circle CI status is blocked 
`Expected — Waiting for status to be reported`

Maybe it's a settings related issue

**Comment by GLOFonseca** [comment]
Hello @SoniaisMad, thanks for your contribution. I will check why ci is not working.

**Review by GLOFonseca — APPROVED** [review]

**Comment by SoniaisMad** [comment]
@GLOFonseca Thanks for the approval ! 
I cannot merge because of the CI issue thought.

**Comment by GLOFonseca** [comment]
@SoniaisMad sorry for the delay, and don't worry about the merge, I will do it this week.
Thanks for your contribution and patience!

**Pull request merged**
